version: "3.0"

services:
  app:
    image: node:18-alpine
    container_name: darksoulsapi
    ports:
      - "3000:3000"
    env_file:
      - .env
    command: sh -c "npm install && npm run build && npm run start"
    volumes:
      - .:/usr/src/app
    working_dir: /usr/src/app
    restart: unless-stopped
